spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/indentity_service"
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /identity




